### ISSUE TITLE
ESDoc2 ERR! Error: ENOENT: no such file or directory, open '...\out\docs\ast\source\.external-ecmascript.js.json'

### ISSUE THREAD

**Issue by phil-lgr** [esdoc2/esdoc2#15]
### Subject of the issue
Describe your issue here.

### Your environment
* Windows 10
* v8.11.1
* 2.1.1

### Steps to reproduce
```
npm i
node scripts\build-package.js
node scripts\build-docs.js
```

### Expected behaviour
Docs are generated

### Actual behaviour
```
ESDoc2 ERR! Error: ENOENT: no such file or directory, open 'C:\Users\Phil\Documents\Code\esdoc2\out\docs\ast\source\.external-ecmascript.js.json'
child_process.js:644
    throw err;
    ^

Error: Command failed: node .\node_modules\esdoc2\out\src\ESDocCLI.js
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Function.execSync [as exec] (C:\Users\Phil\Documents\Code\esdoc2\scripts\sh.js:6:16)
    at Object.<anonymous> (C:\Users\Phil\Documents\Code\esdoc2\scripts\build-docs.js:11:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by phil-lgr** [comment]
Hi there, thanks for forking this version, if I can make it work I'll be willing to help out!

I checkout out from this repo, then `git checkout tags/2.2.0` but I have that error with the missing `.external-ecmascript.js.json` 😅

**Comment by phil-lgr** [comment]
Detailed log while debugging:

```
ESDoc2 WARN ast unknown export declaration type. type = "ClassDeclaration"
parse: C:\Users\Phil\Documents\Code\esdoc2\test\integration-test\package.test.js
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'line' of undefined
    at InvalidCodeLogger.showFile (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2\out\src\Util\InvalidCodeLogger.js:88:38)
    at Plugin._traverse (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:113:25)
    at _walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:66:25)
    at Plugin._walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:91:9)
    at Plugin._walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:93:14)
    at Plugin._generateDocs (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:50:10)
    at Plugin._exec (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:23:23)
    at Plugin.onHandleDocs (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:17:10)
    at Plugin._execHandler (C:\Users\Phil\Documents\Code\esdoc2\out\src\Plugin\Plugin.js:77:30)
    at Plugin.onHandleDocs (C:\Users\Phil\Documents\Code\esdoc2\out\src\Plugin\Plugin.js:190:12) } reason: TypeError: Cannot read property 'line' of undefined
    at InvalidCodeLogger.showFile (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2\out\src\Util\InvalidCodeLogger.js:88:38)
    at Plugin._traverse (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:113:25)
    at _walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:66:25)
    at Plugin._walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:91:9)
    at Plugin._walk (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:93:14)
    at Plugin._generateDocs (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:50:10)
    at Plugin._exec (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:23:23)
    at Plugin.onHandleDocs (C:\Users\Phil\Documents\Code\esdoc2\node_modules\esdoc2-integrate-test-plugin\src\Plugin.js:17:10)
    at Plugin._execHandler (C:\Users\Phil\Documents\Code\esdoc2\out\src\Plugin\Plugin.js:77:30)
    at Plugin.onHandleDocs (C:\Users\Phil\Documents\Code\esdoc2\out\src\Plugin\Plugin.js:190:12)
ESDoc2 ERR! Error: ENOENT: no such file or directory, open 'C:\Users\Phil\Documents\Code\esdoc2\out\docs\ast\source\.external-ecmascript.js.json' 
Debugger attached.
Waiting for the debugger to disconnect...

Process finished with exit code 1
```

**Comment by rgsilva** [comment]
What's in your `node scripts\build-docs.js`? We need to know how exactly you're calling esdoc2. Plus, I'm not sure if Windows is currently supported, even under WSL.

If you could provide the smallest possible example for reproducing the issue would be great as well (all commands, scripts and required test files).

**Comment by phil-lgr** [comment]
I was using this very repo

**Comment by rgsilva** [comment]
Oh sorry, I didn't notice that. Ops! :)

I'll take a look at it and see what's going on. But it might be because currently installations using npm are broken, which can lead to all sort of issues. I'm waiting for @MattMcFarland to give me access so I can try and fix it.

**Comment by phil-lgr** [comment]
Ok.. thanks, I really want to help.. I spent countless hours looking for a documentation tool to include with my apps, starters... ESDoc is our only hope 😭 

I tried with yarn with no luck on Windows.. I will try on Mac to see

**Comment by phil-lgr** [comment]
Are you on Slack or DM on Twitter? I'd like to know how you use ESDoc and your experience regarding documentation... it's a surprisingly hard problem to solve.

**Comment by phil-lgr** [comment]
MacOS 10.13.3 
Node v8.9.4

Works fine with npm install!
```
node scripts/build-package.js
node scripts/build-docs.js
```

Finishes with no errors

**Comment by phil-lgr** [comment]
Trying to see with node 8.11.1 on Mac...

Update: Works fine.. something is wrong on Windows

**Comment by phil-lgr** [comment]
Something is wrong with that `node.loc`, I'm not familiar with estree.... 

![image](https://user-images.githubusercontent.com/9644867/38437377-4382bd2c-39a5-11e8-8a80-d4b5e5e300b2.png)

**Comment by simpleigh** [comment]
I get the same error using `yarn` on Windows:

```
ESDoc2 ERR! Error: ENOENT: no such file or directory, open 'C:\path\to\project\docs\ast\source\.external-ecmascript.js.json'
error Command failed with exit code 1.
```

I can work around this problem by creating the `\docs\ast\source` directory, and then get another error related to a path in my application code:

```
ESDoc2 ERR! Error: ENOENT: no such file or directory, open 'C:\path\to\project\docs\ast\source\elements\Hello\index.js.json'
error Command failed with exit code 1.
```

Again I can work around by created `\docs\ast\source\elements\Hello`.

... so I think this because the tool is trying to create files in directories that don't yet exist, leading to `ENOENT` on Windows. Once the directory exists then writing a file works fine.
