### ISSUE TITLE
Missing npmlog and mkdirp packages on first install

### ISSUE THREAD

**Issue by 22a** [esdoc2/esdoc2#5]
### Subject of the issue
ESDoc2 fails to run in a clean environment.

### Your environment
* version of OS: macOS 10.13.1 (17B1003)
* version of node js: v8.9.1
* version of ESDoc2: 
```json
  "dependencies": {
    "esdoc2": "^2.1.1",
    "esdoc2-standard-plugin": "^2.1.0"
  }
```

### Steps to reproduce
```
mkdir foo && cd foo
```
```
yarn init -y
```
```
yarn add esdoc2 esdoc2-standard-plugin
```
```
./node_modules/.bin/esdoc2
```

### Expected behaviour
I would expect esdoc2 to run and present this message:
```
ESDoc2 info using node@v8.9.1
ESDoc2 info using esdoc2@2.1.1
ESDoc2 info config null
Usage: esdoc [-c esdoc.json]

Options:
  -c specify config file
  -h output usage information
  -v output the version number

esdoc2 finds configuration by the order:
  1. `-c your-esdoc.json`
  2. `.esdoc.json` in current directory
  3. `.esdoc.js` in current directory
  4. `esdoc` property in package.json
```

### Actual behaviour
It complains about a missing `npmlog` package:
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/Factory/DocFactory.js:9:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
and after I
```
yarn add npmlog
```
it complains about a missing `mkdirp` package:
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDoc.js:53:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
finally after I
```
yarn add mkdirp
```

esdoc2 runs successfully.

Are `npmlog` and `mkdirp` expected to be installed globally? If not, could they be added as dependencies to ESDoc2?

**Comment by MattMcFarland** [comment]
Thanks for reporting this, that was a mistake on my part, they should be in dependencies, looks like they were only in devDependencies.  I believe @rgsilva has just fixed this, and I merged the PR

**Comment by 22a** [comment]
Wonderful! Sorry I didn't see https://github.com/esdoc2/esdoc2/issues/2#issuecomment-351353778 or https://github.com/esdoc2/esdoc2/pull/4, closing!

**Comment by MattMcFarland** [comment]
No problem!! I've just pushed a new release which should be live on npm.. thanks again for posting the issue
