### ISSUE TITLE
Missing esdoc2-publish-html-plugin package

### ISSUE THREAD

**Issue by 22a** [esdoc2/esdoc2#6]
### Subject of the issue
ESDoc2 fails to run in a clean environment. It complains about a missing `esdoc2-publish-html-plugin` package.

### Your environment
* version of OS: macOS 10.13.1 (17B1003)
* version of node js: v8.9.1
* version of ESDoc2: 
```json
  "dependencies": {
    "esdoc2": "^2.1.1",
    "esdoc2-standard-plugin": "^2.1.0"
  }
```

### Steps to reproduce
```
mkdir foo && cd foo
```
```
yarn init -y
```
```
yarn add esdoc2 esdoc2-standard-plugin
```
```
echo '{
  "source": "./src",
  "destination": "./docs",
  "plugins": [{"name": "esdoc2-standard-plugin"}]
}' > .esdoc.json
```
```
./node_modules/.bin/esdoc2
```

### Expected behaviour
I would expect esdoc2 to run and present this message:
```
ESDoc2 info using node@v8.9.1
ESDoc2 info using esdoc2@2.1.1
ESDoc2 info config null
Usage: esdoc [-c esdoc.json]

Options:
  -c specify config file
  -h output usage information
  -v output the version number

esdoc2 finds configuration by the order:
  1. `-c your-esdoc.json`
  2. `.esdoc.json` in current directory
  3. `.esdoc.js` in current directory
  4. `esdoc` property in package.json
```

### Actual behaviour
It complains about a missing `esdoc2-publish-html-plugin` package:
```
ESDoc2 info using node@v8.9.1
ESDoc2 info using esdoc2@2.1.1
ESDoc2 info config /Users/peter/Desktop/foo/.esdoc.json
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Cannot find module 'esdoc2-publish-html-plugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Plugin._execHandler (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/Plugin/Plugin.js:70:22)
    at Plugin.onStart (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/Plugin/Plugin.js:111:12)
    at /Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDoc.js:98:26
    at new Promise (<anonymous>)
    at Function.generate (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDoc.js:91:14)
    at ESDocCLI.exec (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDocCLI.js:94:25) code: 'MODULE_NOT_FOUND' } } reason: { Error: Cannot find module 'esdoc2-publish-html-plugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Plugin._execHandler (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/Plugin/Plugin.js:70:22)
    at Plugin.onStart (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/Plugin/Plugin.js:111:12)
    at /Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDoc.js:98:26
    at new Promise (<anonymous>)
    at Function.generate (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDoc.js:91:14)
    at ESDocCLI.exec (/Users/peter/Desktop/foo/node_modules/esdoc2/out/src/ESDocCLI.js:94:25) code: 'MODULE_NOT_FOUND' }
```
and installing it at the root of the project
```
yarn add esdoc2-publish-html-plugin
```
does not resolve the issue.

**Comment by MattMcFarland** [comment]
Hmm, must be an issue with the plugin repo, we'll have to look into this!

**Comment by rgsilva** [comment]
I believe this is because the actual plugin file (https://github.com/esdoc2/esdoc2-plugins/blob/master/packages/esdoc2-publish-html-plugin/package.json#L55) is missing somehow:

```
ricardo@desenv4 ~/tmp9999 $ npm add esdoc2-publish-html-plugin
npm WARN tmp9999 No description
npm WARN tmp9999 No repository field.
npm WARN tmp9999 No license field.

+ esdoc2-publish-html-plugin@2.0.1
added 219 packages in 3.112s
ricardo@desenv4 ~/tmp9999 $ ls -la node_modules/esdoc2-publish-html-plugin/
total 24
drwxrwxr-x   3 ricardo ricardo 4096 dez 13 15:17 .
drwxrwxr-x 197 ricardo ricardo 4096 dez 13 15:17 ..
-rw-rw-r--   1 ricardo ricardo  231 dez 11 09:57 CHANGELOG.md
drwxrwxr-x  10 ricardo ricardo 4096 dez 13 15:17 node_modules
-rw-rw-r--   1 ricardo ricardo 3470 dez 13 15:17 package.json
-rw-rw-r--   1 ricardo ricardo  690 dez 11 09:57 README.md
ricardo@desenv4 ~/tmp9999 $ 
```

**Comment by rgsilva** [comment]
I believe `esdoc2-publish-html-plugin` is the only plugin that actually is built (https://github.com/esdoc2/esdoc2-plugins/blob/master/packages/esdoc2-publish-html-plugin/package.json#L42):

```
ricardo@desenv4 ~/Development/esdoc2-plugins/packages $ grep -r "build" **/package.json
esdoc2-publish-html-plugin/package.json:    "build": "rm -rf ./out/src && babel --out-dir out/src --ignore 'Builder/template' src && cp -a src/Builder/template out/src/Builder/",
ricardo@desenv4 ~/Development/esdoc2-plugins/packages $ 
```

Probably a simple publishing issue, nothing major, as it builds just fine locally :-)

**Comment by screeny05** [comment]
Yes, i can confirm, that building and linking `esdoc2-publish-html-plugin` locally fixed the issue

**Comment by rgsilva** [comment]
@MattMcFarland do you have any updates on this?

For the others, I don't usually run into this issue because we have a fully local build of esdoc2. I actually made a script for this at work (https://pastebin.com/t2ZdCZW3), but _this is unsupported_ and I only do that because I don't feel like dealing with npm when working on esdoc2.

Note: the script isn't a proper solution. The correct thing to do would be wait on a fix in the repo. But, well, sometimes you just need to generate the damn docs to see if everything is working, so... :)

**Comment by MattMcFarland** [comment]
I haven't really spent much time on it. I did pull it down and couldn't
build it, ran into some error, will have to spend more time on it!

**Comment by ericblade** [comment]
Confirm same problem.  Unable to get working using rgsilva's script, either.  Occurs when installed global, from source, or from npm.  rgsilva's script may be wonky for me because i'm mixing it up in Windows. :-) 

Basically, not possible for me to use esdoc2 in my current setup.  :(

**Comment by rgsilva** [comment]
Uh.. I haven't tried my script on Windows, sorry :/ But if you look at the source code it shouldn't be too difficult to figure out what it is going on. I've deployed it a few days ago and as far as I know it's working just fine. But, unfortunately, it isn't on Windows.

Nevertheless, @MattMcFarland, do you have any updates on this?

**Comment by ericblade** [comment]
yeah, I tried to get really crafty and run your script in WSL, then point my CMD to try to use it, which probably made it a little more difficult.  I suspect it'd probably work if I were running my node environment completely in WSL, but I prefer to work on the native Windows side whenever possible, as WSL is quite slow when there's lots of disk access, such as when starting a node module with a lot of dependencies.

**Comment by rgsilva** [comment]
Yeah WSL is painfully slow for I/O. Found that when playing with ffmpeg recently. Painfully slow at the point a VM was faster.

If you feel like it, you can always try to do what the script is supposed to do. The process is a bit big but it's quite simple:

1. Clone into the current folder `esdoc2` and `esdoc2-plugins` repositories.
2. Patch `esdoc2` by removing any `esdoc2-*` package from its package.json (so it won't download it from the repository).
3. Patch every single `esdoc2-*` plugin for the same thing as `esdoc2`, removing all dependencies between the plugins themselves and `esdoc2` as well.

At this point all packages should have no references to each other at all.

4. Run `npm install` on `esdoc2` root and the same on the root of every plugin (`esdoc2-*`).
5. Build all plugins that require building. The idea here is to check if the plugin requires building (there's a `build` rule in the package.json), and if there's one, you should run `npm run build`.
6. Build `esdoc2` by running `yarn build:package`.

Once everything has been built, you have to relink everything. You can do this manually by checking which package requires which, or you can do as I do, which is to link everything to everything.

7. Make a symbolic link from every plugin (`esdoc2-*`) into `esdoc2/node_modules/`.
8. Make a symbolic link from `esdoc2` into every plugin (`esdoc2-*/node_modules`).

After all of that, you should be ablet o run esdoc2 by running `esdoc2/out/src/ESDocCLI.js` if I recall correctly. Keep in mind you should be at the project's folder to do so:

```
user@host ~/project$ /path/to/esdoc2/out/src/ESDocCLI.js -c myconfig.json
```

**Comment by MattMcFarland** [comment]
Sorry guys, I've been encumbered with a lot of other things, so I'd like to make sure this project doesn't die, and would be happy to add you guys as contributors to the npm package so you can push updates.  Let me know if this sounds good to you and what your npm user name and email is so I can add you as a contributor.

**Comment by ericblade** [comment]
I don't know anything about how to fix it, and don't really have any time to pick up a new thing right at the moment. I would like to see it fixed, though, as it seems the original isn't taking much in

**Comment by rgsilva** [comment]
Sorry, I've switched jobs for now we don't use esdoc2 (sadly), so I've been away for a while.

@MattMcFarland I honestly have zero knowledge of npm to publish a fix for this issue, but I guess I could try to take a look at it? Unfortunately I can't really (at least actively) maintain the project, but I could try to keep an eye on it during my spare time so it doesn't die.

If you want, I could try to fix the publishing issue (which requires some studying - but hey that's what we are here for, right?) and at https://github.com/esdoc2/esdoc2/issues/12 as well at the same time.

What do you think? And what would be the best way to get in touch with you?

**Comment by MattMcFarland** [comment]
@rgsilva yes sorry it took 7 days to respond, if you have time, that would be great..  This project needs some additional maintainers, who can publish to npm.  All you need is an npm account then I can add you as a contributor to `package.json`, which will allow you to run `npm publish`

**Comment by rgsilva** [comment]
@MattMcFarland ha, meanwhile it took me almost a month to reply. But nevertheless, I've found time for personal projects, and that includes esdoc2! :) Anyway, my npm account is rgsilva, just like my github. Ping me when you add me to as contributor so I can start working on these issues.

Soon, guys, soon!
